# Generated by Django 4.1.2 on 2022-11-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentarist', models.TextField(max_length=20)),
                ('text_commentary', models.TextField(max_length=400)),
                ('date_commentary', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(choices=[('TR', 'Travel'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CY', 'Cuyo'), ('PAT', 'Patagonia'), ('MDP', 'Costa Atlántica'), ('BSAS', 'Buenos Aires'), ('COB', 'Centro'), ('PN', 'Parques'), ('LG', 'Lagos'), ('RN', 'Rutas'), ('MNT', 'Montañas'), ('ID', 'Ideas'), ('TIP', 'Rata-tips')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=20)),
                ('begin_date', models.DateTimeField()),
            ],
        ),
    ]
