# Generated by Django 4.1.2 on 2022-11-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques_nacionales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='e_mail',
            field=models.EmailField(default='not_provide@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.TextField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
