# Generated by Django 4.1.2 on 2022-11-19 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parques_nacionales', '0002_remove_users_id_users_e_mail_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag1',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 19)),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image_title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='readmore_avaliable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.TextField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tag2',
            field=models.CharField(choices=[('TR', 'Travel'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CY', 'Cuyo'), ('PAT', 'Patagonia'), ('MDP', 'Costa Atlántica'), ('BSAS', 'Buenos Aires'), ('COB', 'Centro'), ('PN', 'Parques'), ('LG', 'Lagos'), ('RN', 'Rutas'), ('MNT', 'Montañas'), ('ID', 'Ideas'), ('TIP', 'Rata-tips')], default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
